CXX = g++
CXXFLAGS = -Wall -g

TARGET = Problem1

SRCS = BilanganTerbesar.cpp
TEST_SRC = BilanganTerbesar.cpp

all: $(TARGET)

$(TARGET): $(SRCS)
	$(CXX) $(CXXFLAGS) -o
$(TARGET) $(SRCS)

clean:
	rm -f $(TARGET)

clean_all:
	rm -f $(TARGET) *.o

test: